class Report:

    def show(self, model={}):
        print self.fetch(model)

    def fetch(self, model={}):
        import copy   # used by scope
        self.model = model
        scope = model
        scope_stack = []
        zres = ""
        zres = zres + '<'
        zres = zres + 'tr'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'td'
        zres = zres + '>'
        zres = zres + 'first name:'
        zres = zres + '<'
        zres = zres + '/td'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'td'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'input type=\"text\" name=\"fname\" value=\"\"'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + '/td'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + '/tr'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'tr'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'td'
        zres = zres + '>'
        zres = zres + 'last name:'
        zres = zres + '<'
        zres = zres + '/td'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'td'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'input type=\"text\" name=\"lname\" value=\"\"'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + '/td'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'tr'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'tr'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'td'
        zres = zres + '>'
        zres = zres + 'address 1:'
        zres = zres + '<'
        zres = zres + '/td'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'td'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'input type=\"text\" name=\"address1\" value=\"\"'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + '/td'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + '/tr'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'tr'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'td'
        zres = zres + '>'
        zres = zres + 'address 2:'
        zres = zres + '<'
        zres = zres + '/td'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'td'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'input type=\"text\" name=\"address2\" value=\"\"'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + '/td'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + '/tr'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'tr'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'td'
        zres = zres + '>'
        zres = zres + 'address 3:'
        zres = zres + '<'
        zres = zres + '/td'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'td'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'input type=\"text\" name=\"address3\" value=\"\"'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + '/td'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + '/tr'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'tr'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'td'
        zres = zres + '>'
        zres = zres + 'city:'
        zres = zres + '<'
        zres = zres + '/td'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'td'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'input type=\"text\" name=\"city\" value=\"\"'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + '/td'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + '/tr'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'tr'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'td'
        zres = zres + '>'
        zres = zres + 'state, zip:'
        zres = zres + '<'
        zres = zres + '/td'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'td'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'input type=\"text\" size=\"2\" name=\"stateCD\" value=\"\"'
        zres = zres + '>'
        zres = zres + '&'
        zres = zres + 'nbsp;\n         '
        zres = zres + '<'
        zres = zres + 'input type=\"text\" name=\"postal\" size=\"5\" value=\"\"'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + '/td'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + '/tr'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'tr'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'td'
        zres = zres + '>'
        zres = zres + 'country: '
        zres = zres + '<'
        zres = zres + '/td'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'td'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'select name=\"countryCD\"'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"AF\"'
        zres = zres + '>'
        zres = zres + 'Afghanistan'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"AL\"'
        zres = zres + '>'
        zres = zres + 'Albania'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"DZ\"'
        zres = zres + '>'
        zres = zres + 'Algeria'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"AS\"'
        zres = zres + '>'
        zres = zres + 'American Samoa'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"AD\"'
        zres = zres + '>'
        zres = zres + 'Andorra'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"AO\"'
        zres = zres + '>'
        zres = zres + 'Angola'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"AI\"'
        zres = zres + '>'
        zres = zres + 'Anguilla'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"AQ\"'
        zres = zres + '>'
        zres = zres + 'Antarctica'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"AG\"'
        zres = zres + '>'
        zres = zres + 'Antigua and Barbuda'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"AR\"'
        zres = zres + '>'
        zres = zres + 'Argentina'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"AM\"'
        zres = zres + '>'
        zres = zres + 'Armenia'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"AW\"'
        zres = zres + '>'
        zres = zres + 'Aruba'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"AU\"'
        zres = zres + '>'
        zres = zres + 'Australia'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"AT\"'
        zres = zres + '>'
        zres = zres + 'Austria'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"AZ\"'
        zres = zres + '>'
        zres = zres + 'Azerbaijan'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"BS\"'
        zres = zres + '>'
        zres = zres + 'Bahamas'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"BH\"'
        zres = zres + '>'
        zres = zres + 'Bahrain'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"BD\"'
        zres = zres + '>'
        zres = zres + 'Bangladesh'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"BB\"'
        zres = zres + '>'
        zres = zres + 'Barbados'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"BY\"'
        zres = zres + '>'
        zres = zres + 'Belarus'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"BE\"'
        zres = zres + '>'
        zres = zres + 'Belgium'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"BZ\"'
        zres = zres + '>'
        zres = zres + 'Belize'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"BJ\"'
        zres = zres + '>'
        zres = zres + 'Benin'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"BM\"'
        zres = zres + '>'
        zres = zres + 'Bermuda'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"BT\"'
        zres = zres + '>'
        zres = zres + 'Bhutan'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"BO\"'
        zres = zres + '>'
        zres = zres + 'Bolivia'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"BA\"'
        zres = zres + '>'
        zres = zres + 'Bosnia and Herzegovina'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"BW\"'
        zres = zres + '>'
        zres = zres + 'Botswana'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"BV\"'
        zres = zres + '>'
        zres = zres + 'Bouvet Island'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"BR\"'
        zres = zres + '>'
        zres = zres + 'Brazil'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"IO\"'
        zres = zres + '>'
        zres = zres + 'British Indian Ocean Territory'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"BN\"'
        zres = zres + '>'
        zres = zres + 'Brunei Darussalam'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"BG\"'
        zres = zres + '>'
        zres = zres + 'Bulgaria'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"BF\"'
        zres = zres + '>'
        zres = zres + 'Burkina Faso'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"BI\"'
        zres = zres + '>'
        zres = zres + 'Burundi'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"KH\"'
        zres = zres + '>'
        zres = zres + 'Cambodia'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"CM\"'
        zres = zres + '>'
        zres = zres + 'Cameroon'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"CA\"'
        zres = zres + '>'
        zres = zres + 'Canada'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"CV\"'
        zres = zres + '>'
        zres = zres + 'Cape Verde'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"KY\"'
        zres = zres + '>'
        zres = zres + 'Cayman Islands'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"CF\"'
        zres = zres + '>'
        zres = zres + 'Central African Republic'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"TD\"'
        zres = zres + '>'
        zres = zres + 'Chad'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"CL\"'
        zres = zres + '>'
        zres = zres + 'Chile'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"CN\"'
        zres = zres + '>'
        zres = zres + 'China'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"CX\"'
        zres = zres + '>'
        zres = zres + 'Christmas Island'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"CC\"'
        zres = zres + '>'
        zres = zres + 'Cocos (Keeling) Islands'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"CO\"'
        zres = zres + '>'
        zres = zres + 'Colombia'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"KM\"'
        zres = zres + '>'
        zres = zres + 'Comoros'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"CG\"'
        zres = zres + '>'
        zres = zres + 'Congo'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"CK\"'
        zres = zres + '>'
        zres = zres + 'Cook Islands'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"CR\"'
        zres = zres + '>'
        zres = zres + 'Costa Rica'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"CI\"'
        zres = zres + '>'
        zres = zres + 'Cote D\'Ivoire (Ivory Coast)'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"HR\"'
        zres = zres + '>'
        zres = zres + 'Croatia (Hrvatska)'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"CU\"'
        zres = zres + '>'
        zres = zres + 'Cuba'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"CY\"'
        zres = zres + '>'
        zres = zres + 'Cyprus'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"CZ\"'
        zres = zres + '>'
        zres = zres + 'Czech Republic'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"CS\"'
        zres = zres + '>'
        zres = zres + 'Czechoslovakia (former)'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"DK\"'
        zres = zres + '>'
        zres = zres + 'Denmark'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"DJ\"'
        zres = zres + '>'
        zres = zres + 'Djibouti'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"DM\"'
        zres = zres + '>'
        zres = zres + 'Dominica'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"DO\"'
        zres = zres + '>'
        zres = zres + 'Dominican Republic'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"TP\"'
        zres = zres + '>'
        zres = zres + 'East Timor'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"EC\"'
        zres = zres + '>'
        zres = zres + 'Ecuador'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"EG\"'
        zres = zres + '>'
        zres = zres + 'Egypt'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"SV\"'
        zres = zres + '>'
        zres = zres + 'El Salvador'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"GQ\"'
        zres = zres + '>'
        zres = zres + 'Equatorial Guinea'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"ER\"'
        zres = zres + '>'
        zres = zres + 'Eritrea'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"EE\"'
        zres = zres + '>'
        zres = zres + 'Estonia'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"ET\"'
        zres = zres + '>'
        zres = zres + 'Ethiopia'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"FK\"'
        zres = zres + '>'
        zres = zres + 'Falkland Islands (Malvinas)'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"FO\"'
        zres = zres + '>'
        zres = zres + 'Faroe Islands'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"FJ\"'
        zres = zres + '>'
        zres = zres + 'Fiji'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"FI\"'
        zres = zres + '>'
        zres = zres + 'Finland'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"FR\"'
        zres = zres + '>'
        zres = zres + 'France'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"FX\"'
        zres = zres + '>'
        zres = zres + 'France, Metropolitan'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"GF\"'
        zres = zres + '>'
        zres = zres + 'French Guiana'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"PF\"'
        zres = zres + '>'
        zres = zres + 'French Polynesia'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"TF\"'
        zres = zres + '>'
        zres = zres + 'French Southern Territories'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"GA\"'
        zres = zres + '>'
        zres = zres + 'Gabon'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"GM\"'
        zres = zres + '>'
        zres = zres + 'Gambia'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"GE\"'
        zres = zres + '>'
        zres = zres + 'Georgia'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"DE\"'
        zres = zres + '>'
        zres = zres + 'Germany'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"GH\"'
        zres = zres + '>'
        zres = zres + 'Ghana'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"GI\"'
        zres = zres + '>'
        zres = zres + 'Gibraltar'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"GB\"'
        zres = zres + '>'
        zres = zres + 'Great Britain (UK)'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"GR\"'
        zres = zres + '>'
        zres = zres + 'Greece'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"GL\"'
        zres = zres + '>'
        zres = zres + 'Greenland'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"GD\"'
        zres = zres + '>'
        zres = zres + 'Grenada'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"GP\"'
        zres = zres + '>'
        zres = zres + 'Guadeloupe'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"GU\"'
        zres = zres + '>'
        zres = zres + 'Guam'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"GT\"'
        zres = zres + '>'
        zres = zres + 'Guatemala'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"GN\"'
        zres = zres + '>'
        zres = zres + 'Guinea'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"GW\"'
        zres = zres + '>'
        zres = zres + 'Guinea-Bissau'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"GY\"'
        zres = zres + '>'
        zres = zres + 'Guyana'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"HT\"'
        zres = zres + '>'
        zres = zres + 'Haiti'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"HM\"'
        zres = zres + '>'
        zres = zres + 'Heard and McDonald Islands'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"HN\"'
        zres = zres + '>'
        zres = zres + 'Honduras'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"HK\"'
        zres = zres + '>'
        zres = zres + 'Hong Kong'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"HU\"'
        zres = zres + '>'
        zres = zres + 'Hungary'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"IS\"'
        zres = zres + '>'
        zres = zres + 'Iceland'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"IN\"'
        zres = zres + '>'
        zres = zres + 'India'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"ID\"'
        zres = zres + '>'
        zres = zres + 'Indonesia'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"IR\"'
        zres = zres + '>'
        zres = zres + 'Iran'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"IQ\"'
        zres = zres + '>'
        zres = zres + 'Iraq'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"IE\"'
        zres = zres + '>'
        zres = zres + 'Ireland'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"IL\"'
        zres = zres + '>'
        zres = zres + 'Israel'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"IT\"'
        zres = zres + '>'
        zres = zres + 'Italy'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"JM\"'
        zres = zres + '>'
        zres = zres + 'Jamaica'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"JP\"'
        zres = zres + '>'
        zres = zres + 'Japan'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"JO\"'
        zres = zres + '>'
        zres = zres + 'Jordan'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"KZ\"'
        zres = zres + '>'
        zres = zres + 'Kazakhstan'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"KE\"'
        zres = zres + '>'
        zres = zres + 'Kenya'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"KI\"'
        zres = zres + '>'
        zres = zres + 'Kiribati'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"KP\"'
        zres = zres + '>'
        zres = zres + 'Korea (North)'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"KR\"'
        zres = zres + '>'
        zres = zres + 'Korea (South)'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"KW\"'
        zres = zres + '>'
        zres = zres + 'Kuwait'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"KG\"'
        zres = zres + '>'
        zres = zres + 'Kyrgyzstan'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"LA\"'
        zres = zres + '>'
        zres = zres + 'Laos'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"LV\"'
        zres = zres + '>'
        zres = zres + 'Latvia'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"LB\"'
        zres = zres + '>'
        zres = zres + 'Lebanon'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"LS\"'
        zres = zres + '>'
        zres = zres + 'Lesotho'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"LR\"'
        zres = zres + '>'
        zres = zres + 'Liberia'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"LY\"'
        zres = zres + '>'
        zres = zres + 'Libya'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"LI\"'
        zres = zres + '>'
        zres = zres + 'Liechtenstein'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"LT\"'
        zres = zres + '>'
        zres = zres + 'Lithuania'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"LU\"'
        zres = zres + '>'
        zres = zres + 'Luxembourg'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"MO\"'
        zres = zres + '>'
        zres = zres + 'Macau'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"MK\"'
        zres = zres + '>'
        zres = zres + 'Macedonia'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"MG\"'
        zres = zres + '>'
        zres = zres + 'Madagascar'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"MW\"'
        zres = zres + '>'
        zres = zres + 'Malawi'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"MY\"'
        zres = zres + '>'
        zres = zres + 'Malaysia'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"MV\"'
        zres = zres + '>'
        zres = zres + 'Maldives'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"ML\"'
        zres = zres + '>'
        zres = zres + 'Mali'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"MT\"'
        zres = zres + '>'
        zres = zres + 'Malta'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"MH\"'
        zres = zres + '>'
        zres = zres + 'Marshall Islands'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"MQ\"'
        zres = zres + '>'
        zres = zres + 'Martinique'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"MR\"'
        zres = zres + '>'
        zres = zres + 'Mauritania'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"MU\"'
        zres = zres + '>'
        zres = zres + 'Mauritius'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"YT\"'
        zres = zres + '>'
        zres = zres + 'Mayotte'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"MX\"'
        zres = zres + '>'
        zres = zres + 'Mexico'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"FM\"'
        zres = zres + '>'
        zres = zres + 'Micronesia'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"MD\"'
        zres = zres + '>'
        zres = zres + 'Moldova'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"MC\"'
        zres = zres + '>'
        zres = zres + 'Monaco'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"MN\"'
        zres = zres + '>'
        zres = zres + 'Mongolia'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"MS\"'
        zres = zres + '>'
        zres = zres + 'Montserrat'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"MA\"'
        zres = zres + '>'
        zres = zres + 'Morocco'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"MZ\"'
        zres = zres + '>'
        zres = zres + 'Mozambique'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"MM\"'
        zres = zres + '>'
        zres = zres + 'Myanmar'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"NA\"'
        zres = zres + '>'
        zres = zres + 'Namibia'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"NR\"'
        zres = zres + '>'
        zres = zres + 'Nauru'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"NP\"'
        zres = zres + '>'
        zres = zres + 'Nepal'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"NL\"'
        zres = zres + '>'
        zres = zres + 'Netherlands'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"AN\"'
        zres = zres + '>'
        zres = zres + 'Netherlands Antilles'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"NT\"'
        zres = zres + '>'
        zres = zres + 'Neutral Zone'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"NC\"'
        zres = zres + '>'
        zres = zres + 'New Caledonia'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"NZ\"'
        zres = zres + '>'
        zres = zres + 'New Zealand (Aotearoa)'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"NI\"'
        zres = zres + '>'
        zres = zres + 'Nicaragua'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"NE\"'
        zres = zres + '>'
        zres = zres + 'Niger'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"NG\"'
        zres = zres + '>'
        zres = zres + 'Nigeria'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"NU\"'
        zres = zres + '>'
        zres = zres + 'Niue'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"NF\"'
        zres = zres + '>'
        zres = zres + 'Norfolk Island'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"MP\"'
        zres = zres + '>'
        zres = zres + 'Northern Mariana Islands'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"NO\"'
        zres = zres + '>'
        zres = zres + 'Norway'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"OM\"'
        zres = zres + '>'
        zres = zres + 'Oman'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"PK\"'
        zres = zres + '>'
        zres = zres + 'Pakistan'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"PW\"'
        zres = zres + '>'
        zres = zres + 'Palau'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"PA\"'
        zres = zres + '>'
        zres = zres + 'Panama'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"PG\"'
        zres = zres + '>'
        zres = zres + 'Papua New Guinea'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"PY\"'
        zres = zres + '>'
        zres = zres + 'Paraguay'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"PE\"'
        zres = zres + '>'
        zres = zres + 'Peru'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"PH\"'
        zres = zres + '>'
        zres = zres + 'Philippines'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"PN\"'
        zres = zres + '>'
        zres = zres + 'Pitcairn'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"PL\"'
        zres = zres + '>'
        zres = zres + 'Poland'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"PT\"'
        zres = zres + '>'
        zres = zres + 'Portugal'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"PR\"'
        zres = zres + '>'
        zres = zres + 'Puerto Rico'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"QA\"'
        zres = zres + '>'
        zres = zres + 'Qatar'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"RE\"'
        zres = zres + '>'
        zres = zres + 'Reunion'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"RO\"'
        zres = zres + '>'
        zres = zres + 'Romania'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"RU\"'
        zres = zres + '>'
        zres = zres + 'Russian Federation'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"RW\"'
        zres = zres + '>'
        zres = zres + 'Rwanda'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"GS\"'
        zres = zres + '>'
        zres = zres + 'S. Georgia and S. Sandwich Isls.'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"KN\"'
        zres = zres + '>'
        zres = zres + 'Saint Kitts and Nevis'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"LC\"'
        zres = zres + '>'
        zres = zres + 'Saint Lucia'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"VC\"'
        zres = zres + '>'
        zres = zres + 'Saint Vincent and the Grenadines'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"WS\"'
        zres = zres + '>'
        zres = zres + 'Samoa'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"SM\"'
        zres = zres + '>'
        zres = zres + 'San Marino'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"ST\"'
        zres = zres + '>'
        zres = zres + 'Sao Tome and Principe'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"SA\"'
        zres = zres + '>'
        zres = zres + 'Saudi Arabia'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"SN\"'
        zres = zres + '>'
        zres = zres + 'Senegal'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"SC\"'
        zres = zres + '>'
        zres = zres + 'Seychelles'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"SL\"'
        zres = zres + '>'
        zres = zres + 'Sierra Leone'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"SG\"'
        zres = zres + '>'
        zres = zres + 'Singapore'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"SK\"'
        zres = zres + '>'
        zres = zres + 'Slovak Republic'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"SI\"'
        zres = zres + '>'
        zres = zres + 'Slovenia'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"Sb\"'
        zres = zres + '>'
        zres = zres + 'Solomon Islands'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"SO\"'
        zres = zres + '>'
        zres = zres + 'Somalia'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"ZA\"'
        zres = zres + '>'
        zres = zres + 'South Africa'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"ES\"'
        zres = zres + '>'
        zres = zres + 'Spain'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"LK\"'
        zres = zres + '>'
        zres = zres + 'Sri Lanka'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"SH\"'
        zres = zres + '>'
        zres = zres + 'St. Helena'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"PM\"'
        zres = zres + '>'
        zres = zres + 'St. Pierre and Miquelon'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"SD\"'
        zres = zres + '>'
        zres = zres + 'Sudan'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"SR\"'
        zres = zres + '>'
        zres = zres + 'Suriname'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"SJ\"'
        zres = zres + '>'
        zres = zres + 'Svalbard and Jan Mayen Islands'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"SZ\"'
        zres = zres + '>'
        zres = zres + 'Swaziland'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"SE\"'
        zres = zres + '>'
        zres = zres + 'Sweden'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"CH\"'
        zres = zres + '>'
        zres = zres + 'Switzerland'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"SY\"'
        zres = zres + '>'
        zres = zres + 'Syria'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"TW\"'
        zres = zres + '>'
        zres = zres + 'Taiwan'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"TJ\"'
        zres = zres + '>'
        zres = zres + 'Tajikistan'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"TZ\"'
        zres = zres + '>'
        zres = zres + 'Tanzania'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"TH\"'
        zres = zres + '>'
        zres = zres + 'Thailand'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"TG\"'
        zres = zres + '>'
        zres = zres + 'Togo'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"TK\"'
        zres = zres + '>'
        zres = zres + 'Tokelau'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"TO\"'
        zres = zres + '>'
        zres = zres + 'Tonga'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"TT\"'
        zres = zres + '>'
        zres = zres + 'Trinidad and Tobago'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"TN\"'
        zres = zres + '>'
        zres = zres + 'Tunisia'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"TR\"'
        zres = zres + '>'
        zres = zres + 'Turkey'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"TM\"'
        zres = zres + '>'
        zres = zres + 'Turkmenistan'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"TC\"'
        zres = zres + '>'
        zres = zres + 'Turks and Caicos Islands'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"TV\"'
        zres = zres + '>'
        zres = zres + 'Tuvalu'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"UG\"'
        zres = zres + '>'
        zres = zres + 'Uganda'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"UA\"'
        zres = zres + '>'
        zres = zres + 'Ukraine'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"AE\"'
        zres = zres + '>'
        zres = zres + 'United Arab Emirates'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"UK\"'
        zres = zres + '>'
        zres = zres + 'United Kingdom'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"US\" SELECTED'
        zres = zres + '>'
        zres = zres + 'United States'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"UY\"'
        zres = zres + '>'
        zres = zres + 'Uruguay'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"UM\"'
        zres = zres + '>'
        zres = zres + 'US Minor Outlying Islands'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"SU\"'
        zres = zres + '>'
        zres = zres + 'USSR (former)'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"UZ\"'
        zres = zres + '>'
        zres = zres + 'Uzbekistan'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"VU\"'
        zres = zres + '>'
        zres = zres + 'Vanuatu'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"VA\"'
        zres = zres + '>'
        zres = zres + 'Vatican City State (Holy See)'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"VE\"'
        zres = zres + '>'
        zres = zres + 'Venezuela'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"VN\"'
        zres = zres + '>'
        zres = zres + 'Viet Nam'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"VG\"'
        zres = zres + '>'
        zres = zres + 'Virgin Islands (British)'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"VI\"'
        zres = zres + '>'
        zres = zres + 'Virgin Islands (U.S.)'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"WF\"'
        zres = zres + '>'
        zres = zres + 'Wallis and Futuna Islands'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"EH\"'
        zres = zres + '>'
        zres = zres + 'Western Sahara'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"YE\"'
        zres = zres + '>'
        zres = zres + 'Yemen'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"YU\"'
        zres = zres + '>'
        zres = zres + 'Yugoslavia'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"ZR\"'
        zres = zres + '>'
        zres = zres + 'Zaire'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"ZM\"'
        zres = zres + '>'
        zres = zres + 'Zambia'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option value=\"ZW\"'
        zres = zres + '>'
        zres = zres + 'Zimbabwe'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + '/select'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + '/td'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + '/tr'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'tr'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'td'
        zres = zres + '>'
        zres = zres + 'phone:'
        zres = zres + '<'
        zres = zres + '/td'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'td'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'input type=\"text\" name=\"phone\" value=\"\"'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + '/td'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + '/tr'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'tr'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'td colspan=\"2\" align=\"right\"'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'input type=\"submit\" name=\"action\" value=\"save\"'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + '/td'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + '/tr'
        zres = zres + '>'
# end of Report.fetch()
        return zres

def fetch(model={}):
    return Report().fetch(model)
    
def show(model={}):
    return Report().show(model)
