class Report:

    def show(self, model={}):
        print self.fetch(model)

    def fetch(self, model={}):
        import copy   # used by scope
        self.model = model
        scope = model
        scope_stack = []
        zres = ""
        import tpl_head
        zres = zres+ tpl_head.fetch(scope)
        zres = zres + '<'
        zres = zres + 'h1'
        zres = zres + '>'
        zres = zres + str(scope.get('message',''))
        zres = zres + '<'
        zres = zres + '/h1'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'h3'
        zres = zres + '>'
        zres = zres + 'You may enter existing account info:'
        zres = zres + '<'
        zres = zres + '/h3'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'form action=\"'
        zres = zres + str(scope.get('action',''))
        zres = zres + '\" method=\"post\"'
        zres = zres + '>'
        zres = zres + str(scope.get('hidden',''))
        zres = zres + '\nemail: '
        zres = zres + '<'
        zres = zres + 'input type=\"text\" name=\"auth_email\"'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'br'
        zres = zres + '>'
        zres = zres + '\npassword: '
        zres = zres + '<'
        zres = zres + 'input type=\"password\" name=\"auth_password\"'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'br'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'input type=\"submit\"'
        zres = zres + '>'
        zres = zres + '\n['
        zres = zres + '<'
        zres = zres + 'a href=\"password.py\"'
        zres = zres + '>'
        zres = zres + 'forgot your password?'
        zres = zres + '<'
        zres = zres + '/a'
        zres = zres + '>'
        zres = zres + ']'
        zres = zres + '<'
        zres = zres + '/form'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'h3'
        zres = zres + '>'
        zres = zres + '...or create a new account:'
        zres = zres + '<'
        zres = zres + '/h3'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'form action=\"newcustomer.py\" method=\"post\"'
        zres = zres + '>'
        zres = zres + '\nemail: '
        zres = zres + '<'
        zres = zres + 'input type=\"text\" name=\"email\" value=\"\"'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'br'
        zres = zres + '>'
        zres = zres + '\ncreate a password:'
        zres = zres + '<'
        zres = zres + 'input type=\"password\" name=\"password\" value=\"\"'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'br'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'hr'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'b'
        zres = zres + '>'
        zres = zres + 'name:'
        zres = zres + '<'
        zres = zres + '/b'
        zres = zres + '>'
        zres = zres + '\nfirst: '
        zres = zres + '<'
        zres = zres + 'input type=\"text\" name=\"fname\" value=\"\"'
        zres = zres + '>'
        zres = zres + '\nlast: '
        zres = zres + '<'
        zres = zres + 'input type=\"text\" name=\"lname\" value=\"\"'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'br'
        zres = zres + '>'
        zres = zres + '\naddress 1: '
        zres = zres + '<'
        zres = zres + 'input type=\"text\" name=\"address1\" value=\"\"'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'br'
        zres = zres + '>'
        zres = zres + '\naddress 2: '
        zres = zres + '<'
        zres = zres + 'input type=\"text\" name=\"address2\" value=\"\"'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'br'
        zres = zres + '>'
        zres = zres + '\naddress 3: '
        zres = zres + '<'
        zres = zres + 'input type=\"text\" name=\"address3\" value=\"\"'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'br'
        zres = zres + '>'
        zres = zres + '\ncity: '
        zres = zres + '<'
        zres = zres + 'input type=\"text\" name=\"city\" value=\"\"'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'br'
        zres = zres + '>'
        zres = zres + '\nstate: '
        zres = zres + '<'
        zres = zres + 'input type=\"text\" size=\"2\" name=\"stateCD\" value=\"\"'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'br'
        zres = zres + '>'
        zres = zres + '\nzip/postal code: '
        zres = zres + '<'
        zres = zres + 'input type=\"text\" name=\"postal\" value=\"\"'
        zres = zres + '>'
        zres = zres + '\ncountry: '
        zres = zres + '<'
        zres = zres + 'input type=\"text\" name=\"countryCD\" value=\"\"'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'br'
        zres = zres + '>'
        zres = zres + '\nphone: '
        zres = zres + '<'
        zres = zres + 'input type=\"text\" name=\"phone\" value=\"\"'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'br'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'input type=\"hidden\" name=\"isPrimary\" value=\"1\"'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'input type=\"submit\" name=\"action\" value=\"save\"'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + '/form'
        zres = zres + '>'
        import tpl_foot
        zres = zres+ tpl_foot.fetch(scope)
# end of Report.fetch()
        return zres

def fetch(model={}):
    return Report().fetch(model)
    
def show(model={}):
    return Report().show(model)
