class Report:

    def show(self, model={}):
        print self.fetch(model)

    def fetch(self, model={}):
        import copy   # used by scope
        self.model = model
        scope = model
        scope_stack = []
        zres = ""
        import tpl_sslhead
        zres = zres+ tpl_sslhead.fetch(scope)
        if scope.get('error',''):
            zres = zres + '<'
            zres = zres + 'h2'
            zres = zres + '>'
            zres = zres + '<'
            zres = zres + 'font color=\"gold\"'
            zres = zres + '>'
            zres = zres + str(scope.get('error',''))
            zres = zres + '<'
            zres = zres + '/font'
            zres = zres + '>'
            zres = zres + '<'
            zres = zres + '/h2'
            zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'h1'
        zres = zres + '>'
        zres = zres + 'Credit Card'
        zres = zres + '<'
        zres = zres + '/h1'
        zres = zres + '>'
        _ = 0
        _max_ = len(self.model["creditcards"])
        scope_stack.append(scope)
        scope = copy.copy(scope)
        scope.update(locals())
        for _ in range(_max_):
            scope.update(self.model["creditcards"][_])
            scope["_"] = _
            if _ == 0:
                zres = zres + '<'
                zres = zres + 'form action=\"checkout.py\" method=\"POST\"'
                zres = zres + '>'
                zres = zres + '<'
                zres = zres + 'h3'
                zres = zres + '>'
                zres = zres + 'Select a credit card from the list below...'
                zres = zres + '<'
                zres = zres + '/h3'
                zres = zres + '>'
                zres = zres + '<'
                zres = zres + 'select name=\"cardID\"'
                zres = zres + '>'
            zres = zres + '<'
            zres = zres + 'option value=\"'
            zres = zres + str(scope.get('ID',''))
            zres = zres + '\"'
            zres = zres + '>'
            zres = zres + str(scope.get('maskedNumber',''))
            zres = zres + '<'
            zres = zres + '/option'
            zres = zres + '>'
            if _ + 1 == _max_:
                zres = zres + '<'
                zres = zres + '/select'
                zres = zres + '>'
                zres = zres + '<'
                zres = zres + 'input type=\"hidden\" name=\"action\" value=\"update\"'
                zres = zres + '>'
                zres = zres + '<'
                zres = zres + 'input type=\"submit\" value=\"submit\"'
                zres = zres + '>'
                zres = zres + '<'
                zres = zres + '/form'
                zres = zres + '>'
            zres = zres + '<'
            zres = zres + 'h3'
            zres = zres + '>'
            zres = zres + '... or enter a new card below:'
            zres = zres + '<'
            zres = zres + '/h3'
            zres = zres + '>'
        scope = scope_stack.pop()
        del _
        if not _max_:
            zres = zres + '<'
            zres = zres + 'h3'
            zres = zres + '>'
            zres = zres + 'enter your credit card info below:'
            zres = zres + '<'
            zres = zres + '/h3'
            zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'form action=\"checkout.py\" method=\"post\"'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'table border=\"0\"'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'tr'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'td'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'b'
        zres = zres + '>'
        zres = zres + 'name on card:'
        zres = zres + '<'
        zres = zres + '/b'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + '/td'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'td'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'input type=\"text\" name=\"name\" value=\"\"'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + '/td'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + '/tr'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'tr'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'td'
        zres = zres + '>'
        zres = zres + 'card number'
        zres = zres + '<'
        zres = zres + '/td'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'td'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'input type=\"text\" name=\"number\"'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + '/td'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + '/tr'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'tr'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'td'
        zres = zres + '>'
        zres = zres + 'expiration date'
        zres = zres + '<'
        zres = zres + '/td'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'td'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'select name=\"expMonth\"'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option'
        zres = zres + '>'
        zres = zres + '01'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option'
        zres = zres + '>'
        zres = zres + '02'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option'
        zres = zres + '>'
        zres = zres + '03'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option'
        zres = zres + '>'
        zres = zres + '04'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option'
        zres = zres + '>'
        zres = zres + '05'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option'
        zres = zres + '>'
        zres = zres + '06'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option'
        zres = zres + '>'
        zres = zres + '07'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option'
        zres = zres + '>'
        zres = zres + '08'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option'
        zres = zres + '>'
        zres = zres + '09'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option'
        zres = zres + '>'
        zres = zres + '10'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option'
        zres = zres + '>'
        zres = zres + '11'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option'
        zres = zres + '>'
        zres = zres + '12'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + '/select'
        zres = zres + '>'
        zres = zres + '\n\n/'
        zres = zres + '<'
        zres = zres + 'select name=\"expYear\"'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option'
        zres = zres + '>'
        zres = zres + '2000'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option'
        zres = zres + '>'
        zres = zres + '2001'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option'
        zres = zres + '>'
        zres = zres + '2002'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option'
        zres = zres + '>'
        zres = zres + '2003'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option'
        zres = zres + '>'
        zres = zres + '2004'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option'
        zres = zres + '>'
        zres = zres + '2005'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option'
        zres = zres + '>'
        zres = zres + '2006'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'option'
        zres = zres + '>'
        zres = zres + '2007'
        zres = zres + '<'
        zres = zres + '/option'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + '/select'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + '/td'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + '/tr'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + '/table'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'br'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'input type=\"hidden\" name=\"context\" value=\"checkout\"'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'input type=\"hidden\" name=\"action\" value=\"addcard\"'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'input type=\"submit\" value=\"submit\"'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + '/form'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'h2'
        zres = zres + '>'
        zres = zres + 'Your Order'
        zres = zres + '<'
        zres = zres + '/h2'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'table border=\"1\"'
        zres = zres + '>'
        _ = 0
        _max_ = len(self.model["products"])
        scope_stack.append(scope)
        scope = copy.copy(scope)
        scope.update(locals())
        for _ in range(_max_):
            scope.update(self.model["products"][_])
            scope["_"] = _
            zres = zres + '<'
            zres = zres + 'tr'
            zres = zres + '>'
            zres = zres + '<'
            zres = zres + 'td'
            zres = zres + '>'
            zres = zres + str(scope.get('label',''))
            if scope.get('quantity','') > 1:
                zres = zres + '<'
                zres = zres + 'b'
                zres = zres + '>'
                zres = zres + '(* '
                zres = zres + str(scope.get('quantity',''))
                zres = zres + ')'
                zres = zres + '<'
                zres = zres + '/b'
                zres = zres + '>'
            zres = zres + '<'
            zres = zres + '/td'
            zres = zres + '>'
            zres = zres + '<'
            zres = zres + 'td align=\"right\"'
            zres = zres + '>'
            zres = zres + '$'
            zres = zres + str(scope.get('subtotal',''))
            zres = zres + '<'
            zres = zres + '/td'
            zres = zres + '>'
            zres = zres + '<'
            zres = zres + '/tr'
            zres = zres + '>'
        scope = scope_stack.pop()
        del _
        zres = zres + '<'
        zres = zres + 'tr'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'td bgcolor=\"#666666\"'
        zres = zres + '>'
        zres = zres + 'SalesTax'
        zres = zres + '<'
        zres = zres + '/td'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'td align=\"right\"'
        zres = zres + '>'
        zres = zres + '$'
        zres = zres + str(scope.get('salestax',''))
        zres = zres + '<'
        zres = zres + '/td'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + '/tr'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'tr'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'td bgcolor=\"#666666\"'
        zres = zres + '>'
        zres = zres + 'Shipping'
        zres = zres + '<'
        zres = zres + '/td'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'td align=\"right\"'
        zres = zres + '>'
        zres = zres + '$'
        zres = zres + str(scope.get('shipping',''))
        zres = zres + '<'
        zres = zres + '/td'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + '/tr'
        zres = zres + '>'
        if scope.get('adjustment',''):
            zres = zres + '<'
            zres = zres + 'tr'
            zres = zres + '>'
            zres = zres + '<'
            zres = zres + 'td bgcolor=\"#666666\"'
            zres = zres + '>'
            zres = zres + 'Adjustment'
            zres = zres + '<'
            zres = zres + '/td'
            zres = zres + '>'
            zres = zres + '<'
            zres = zres + 'td align=\"right\"'
            zres = zres + '>'
            zres = zres + str(scope.get('adjustment',''))
            zres = zres + '<'
            zres = zres + '/td'
            zres = zres + '>'
            zres = zres + '<'
            zres = zres + '/tr'
            zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'tr'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'td bgcolor=\"#000000\"'
        zres = zres + '>'
        zres = zres + 'Total'
        zres = zres + '<'
        zres = zres + '/td'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + 'td align=\"right\"'
        zres = zres + '>'
        zres = zres + '$'
        zres = zres + str(scope.get('total',''))
        zres = zres + '<'
        zres = zres + '/td'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + '/tr'
        zres = zres + '>'
        zres = zres + '<'
        zres = zres + '/table'
        zres = zres + '>'
        import tpl_sslfoot
        zres = zres+ tpl_sslfoot.fetch(scope)
# end of Report.fetch()
        return zres

def fetch(model={}):
    return Report().fetch(model)
    
def show(model={}):
    return Report().show(model)
