#!/usr/home/sabren/bin/python

# pyweb : a wrapper script for weblib
# inspired by http://www.webtechniques.com/archives/1998/02/kuchling/
#
# USAGE:
#
# Either do #!/your_path/pyweb at the top of your CGI script,
# or save this in your cgi-bin, and do this in your Apache .htaccess file:
#
# Action application/python-script /cgi-bin/pyweb
# AddType application/python-script .py

import os, weblib


eng = weblib.Engine()
eng.script=open(os.environ["PATH_TRANSLATED"])
eng.run()

if eng.result == eng.SUCCESS:
    print eng.response.getHeaders() + eng.response.buffer
else:
    print "Content-Type: text/html"
    print
    print weblib.trim("""
          <html>
          <head>
          <title>pyweb error</title>
          <style type="text/css">
          body, p { font-family: verdana, arial; font-size: 75%; }
          pre { font-size: 120%; }
          pre.traceback { color: red; }
          pre.output{ color : green }
          </style>
          </head>
          """)
    print "<b>pyweb error while running %s</b><br>" % os.environ["PATH_TRANSLATED"]
    print '<pre class="traceback">' + weblib.htmlEncode(eng.error) + "</pre>"

    print "<b>script output:</b>"
    print '<pre class="output">' + \
          eng.response.getHeaders() + \
          eng.response.buffer + \
          "</pre>"
    print "<hr>"
    print '<a href="http://weblib.sourceforge.net/">weblib</a> ' + \
          '(c) copyright 2000 <a href="http://www.zike.net/">Zike Interactive</a>. ' + \
          'All rights reserved.'    
    print "</html>"





