#!/usr/bin/env python

# speed ranking (on hydrogen.sabren.com, 0713.2003)
# Index       :  0.05 sec  - pure python (no persistence)
# MkIndex     :  0.33 sec  - metakit plus two db files
# SQLiteIndex :  2.00 sec  - pure sqlite
# AllMkIndex  : 10.88 sec  - pure metakit

#@TODO: have this run all the tests at once. 

import ransacker, os, profile, sys, time
now = time.asctime

INDEX = "spec/newprof"
FILE  = "test/profile.this"

for ext in [".rki", ".rkw", ".rkp", ".rk"]:
    try:
        os.unlink(INDEX + ext)
    except:
        pass


CLASS = ransacker.MkIndex
#CLASS = ransacker.Index
#CLASS = ransacker.AllMkIndex
idx = CLASS(INDEX)

#idx = ransacker.SQLiteIndex(INDEX + ".rk")

# make sure we have a fresh index

txt = open(FILE).read()


print "START PASS1:", now()
profile.run('idx.addDocument("pass1", txt)')
print "DONE:", now()

sys.exit()


# do it again, but with an existing word file
del idx
if os.path.exists(INDEX+".rki"):
    os.unlink(INDEX+".rki")
idx = CLASS(INDEX)

print "START PASS2:", now()
profile.run('idx.addDocument("pass2", txt)')
print "DONE:", now()

