#!/usr/bin/env python

import ransacker, os, profile, sys, time
now = time.asctime

INDEX = "spec/newprof"
FILE  = "test/profile.this"

#CLASS = ransacker.AllMkIndex
#CLASS = ransacker.MkIndex
#CLASS = ransacker.Index
idx = ransacker.SQLiteIndex(INDEX + ".rk")

# make sure we have a fresh index
for ext in [".rki", ".rkw", ".rkp"]:
    try:
        os.unlink(INDEX + ext)
    except:
        pass


txt = open(FILE).read()


print "START PASS1:", now()
profile.run('idx.addDocument("pass1", txt)')
print "DONE:", now()

#sys.exit()


## # do it again, but with an existing word file
## del idx
## if os.path.exists(INDEX+".rki"):
##     os.unlink(INDEX+".rki")
## idx = CLASS(INDEX)

## print "START PASS2:", now()
## profile.run('idx.addDocument("pass2", txt)')
## print "DONE:", now()

