#!/usr/bin/env python

import ransacker, os, profile, sys, time

# make sure we have a fresh index
try:
    os.unlink("test/profile.rki")
    os.unlink("test/profile.rkw")
except:
    pass


if len(sys.argv) > 1:
    filename = sys.argv[1]
else:
    filename = "test/profile.this"


txt = open(filename).read()
idx = ransacker.Index("test/profile.rki")


now = lambda: time.asctime(time.localtime(time.time()))

print "START PASS1:", now()
profile.run('idx.index("pass1", txt)')
print "DONE:", now()


# do it again, but with an existing word file
del idx
os.unlink("test/profile.rki")
idx = ransacker.Index("test/profile.rki")


print "START PASS2:", now()
profile.run('idx.index("pass2", txt)')
print "DONE:", now()


